# Generated by Django 3.0.3 on 2020-02-27 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('dish_starter', models.CharField(max_length=100)),
                ('dish_main', models.CharField(max_length=100)),
                ('dish_desert', models.CharField(max_length=100)),
                ('starter', models.TextField()),
                ('main', models.TextField()),
                ('desert', models.TextField()),
            ],
        ),
    ]
