# Generated by Django 3.0.3 on 2020-02-27 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissions',
            name='bread',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submissions',
            name='desert',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submissions',
            name='main',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submissions',
            name='starter',
            field=models.TextField(blank=True, null=True),
        ),
    ]
